# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-23 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_token_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(default=uuid.UUID('58744b83-65aa-4a51-994a-8e3ff29c20dc'), max_length=40),
        ),
    ]
